Updated Matrix File

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -25,6 +25,6 @@ jobs:
       - name: Print Configuration
         run: python --version
 
-      - name: Intentional Failure Test (Task 5)
-        if: ${{ matrix.python-version == '3.12' && matrix.os == 'ubuntu-latest' }}
-        run: exit 1
+#      - name: Intentional Failure Test (Task 5)
+#        if: ${{ matrix.python-version == '3.12' && matrix.os == 'ubuntu-latest' }}
+#        run: exit 1
